<a href="https://colab.research.google.com/github/youngpaper1115/Python_Programming_Example/blob/master/python_ex5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**이름: 이종영**

In [2]:
import numpy as np

## 1. 1 부터 9까지의 값을 순차적으로 갖는 3x3 행렬을 생성하시오

In [3]:
z = np.arange(1,10).reshape(3,3)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2.  i번째 열은 원소값으로 모두 (i-1)을 갖는 5x5 행렬을 생성하시오


In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
z = np.zeros((5,5), dtype = float)
z += np.arange(5)

In [6]:
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 3. integer(32 bit) ndarray를 float(32 bit) ndarray로 바꾸려면 어떻게 해야하는가?

In [7]:
z = np.arange(10, dtype=np.int32)

In [8]:
z_new = np.float32(z)
print(z_new)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 4. quest.pickle 파일에는 5점 만점으로 된 설문조사 결과가 배열로 저장되어 있다. 이 파일을 읽어와서 설문조사 결과 5점 초과하는 값이 있는지 살펴보고 있을 경우 모두 5로 변경하여라. 

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
import pickle

In [11]:
#colab을 사용하시는 분들은 이전 과제에서 사용했던 것처럼 google drive mount와 파일 경로 지정을 해주셔야 합니다.
quest = np.load('/content/drive/My Drive/Python_SNU/data/quest.pickle', allow_pickle=True)

In [14]:
quest

array([[1, 2, 1, 2, 2],
       [1, 3, 2, 3, 2],
       [1, 4, 3, 3, 3],
       [2, 5, 4, 4, 4],
       [2, 5, 6, 2, 5],
       [3, 6, 4, 2, 5],
       [3, 5, 4, 1, 6],
       [3, 5, 5, 1, 3]])

In [12]:
quest_new = np.where(quest>5,5,quest)

In [13]:
print(quest_new)

[[1 2 1 2 2]
 [1 3 2 3 2]
 [1 4 3 3 3]
 [2 5 4 4 4]
 [2 5 5 2 5]
 [3 5 4 2 5]
 [3 5 4 1 5]
 [3 5 5 1 3]]
